#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Run this on the EC2 instance to deploy / update the app.
#
# Usage (first time):
#   scp -r . ec2-user@<EC2_IP>:/opt/app
#   ssh ec2-user@<EC2_IP> "bash /opt/app/scripts/deploy.sh"
#
# Usage (update):
#   ssh ec2-user@<EC2_IP> "cd /opt/app && git pull && bash scripts/deploy.sh"
# =============================================================================
set -euo pipefail

APP_DIR="/opt/app"
REGION="${AWS_REGION:-us-east-1}"
SECRET_NAME="ai-learning/db-credentials"

echo "==> [1/6] Fetching DB credentials from Secrets Manager..."
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_NAME" \
  --region "$REGION" \
  --query SecretString \
  --output text)

DB_USER=$(echo "$SECRET_JSON"     | python3 -c "import sys,json; print(json.load(sys.stdin)['username'])")
DB_PASSWORD=$(echo "$SECRET_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")

# RDS endpoint is passed as env var from CDK output or set manually
DB_HOST="${DB_HOST:-}"
DB_NAME="${DB_NAME:-ailearning}"
DB_PORT="${DB_PORT:-5432}"

echo "==> [2/6] Writing .env file..."
cat > "$APP_DIR/backend/.env" << EOF
# Auto-generated by deploy.sh — do not edit manually
PORT=4000
AWS_REGION=${REGION}
S3_BUCKET_NAME=${S3_BUCKET_NAME}
BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-anthropic.claude-3-haiku-20240307-v1:0}

# RDS
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF

echo "==> [3/6] Installing backend dependencies..."
cd "$APP_DIR/backend"
npm install --omit=dev

echo "==> [4/6] Building frontend..."
cd "$APP_DIR/frontend"
npm install
npm run build

echo "==> [5/6] Starting / restarting backend with PM2..."
cd "$APP_DIR/backend"
pm2 describe ai-learning-backend > /dev/null 2>&1 \
  && pm2 restart ai-learning-backend \
  || pm2 start index.js --name ai-learning-backend --update-env

pm2 save
pm2 startup systemd -u ec2-user --hp /home/ec2-user | tail -1 | bash || true

echo "==> [6/6] Reloading nginx..."
sudo nginx -t && sudo systemctl reload nginx

echo ""
echo "✅  Deploy complete!"
echo "    App is live at: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
